language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

services: postgresql
before_script:
  - psql -c 'create database pgwrapper_test' -U postgres -h 127.0.0.1
  - cp tests/config.php.travis tests/config.php

install:
  - |
    # ignore PHP version on nightly when installing PHPUnit
    if [[ $TRAVIS_PHP_VERSION == "nightly" ]]; then
      composer install --ignore-platform-reqs
    else
      composer install
    fi
script: vendor/bin/phpunit --configuration tests/phpunit.xml
